sudo: false
cache: bundler
language: ruby

rvm:
  - 2.3.0
  - 2.2.4
  - 2.2.0
  - 2.1.8
  - 2.1.0
  - 2.0.0-p648
  - 2.0.0
  - ruby
  - ruby-head
  - jruby-9.1.5.0
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2
  - rbx-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-head

notifications:
  email:
    recipients:
      - johncwang@gmail.com
    on_success: always
    on_failure: always
  webhooks:
    - https://zapier.com/hooks/catch/2y1h4a/
